version: '3'

services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: hybrid-platform-mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - hybrid-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hybrid-platform-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/hybrid-platform?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_VIDEO_BUCKET=${S3_VIDEO_BUCKET}
      - S3_THUMBNAIL_BUCKET=${S3_THUMBNAIL_BUCKET}
      - CLOUDFRONT_VIDEO_DOMAIN=${CLOUDFRONT_VIDEO_DOMAIN}
      - CLOUDFRONT_THUMBNAIL_DOMAIN=${CLOUDFRONT_THUMBNAIL_DOMAIN}
      - CLIENT_URL=${CLIENT_URL}
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - hybrid-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hybrid-platform-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=${API_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - hybrid-network

  # Redis for caching and real-time features
  redis:
    image: redis:latest
    container_name: hybrid-platform-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - hybrid-network

  # Nginx for SSL termination and load balancing
  nginx:
    image: nginx:latest
    container_name: hybrid-platform-nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - hybrid-network

networks:
  hybrid-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
